name: Deploy Worker
on:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "latest"
        cache: "npm"

    - name: Instalar módulos
      run: npm i wrangler@latest

    - name: Build
      run: npx wrangler build

    - name: Adicionar Cabeçalho
      run: cp ${{ github.workspace }}/dist/worker.js ${{ github.workspace }}/dist/worker-original.js && echo -e "/*!\n  * v2ray Subscription Worker (${{ github.sha }})\n  * Copyright 2024 Vahid Farid (https://twitter.com/vahidfarid)\n  * Licensed under GPLv3 (https://github.com/vfarid/v2ray-worker/blob/main/Licence.md)\n  */\n\n$(cat ${{ github.workspace }}/dist/worker.js)" > ${{ github.workspace }}/dist/worker.js

    - name: Deploy
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      run: sed -i "s/KV_NAME/22c94fa17d5e4123a79944b0164376d3/g" wrangler.toml && wrangler deploy --api-token $API_TOKEN --account-id $ACCOUNT_ID
